export const WORDS_EN: string[] = [
  "apple", "banana", "cat", "dog", "elephant", "fire", "guitar", "house",
  "island", "jungle", "kite", "lion", "moon", "ninja", "ocean", "piano",
  "queen", "robot", "snake", "tree", "umbrella", "volcano", "whale", "xylophone",
  "yacht", "zebra", "airplane", "balloon", "castle", "dinosaur", "eagle",
  "flower", "ghost", "helicopter", "iceberg", "jellyfish", "kangaroo", "ladder",
  "mountain", "necklace", "octopus", "penguin", "rainbow", "scissors", "tornado",
  "unicorn", "vampire", "waterfall", "wizard", "angel", "bridge", "candle",
  "diamond", "envelope", "fountain", "globe", "hammer", "igloo", "jewel",
  "knight", "lighthouse", "magnet", "notebook", "owl", "pyramid", "rocket",
  "skeleton", "telescope", "village", "windmill", "compass", "dragon",
  "feather", "giraffe", "headphones", "ice cream", "jacket", "keyboard",
  "lemon", "mushroom", "newspaper", "parachute", "quarter", "refrigerator",
  "surfboard", "toaster", "backpack", "cactus", "dolphin", "explosion",
  "fireplace", "gorilla", "hurricane", "invention", "jigsaw", "koala",
  "labyrinth", "microscope", "nightmare", "orchestra", "platypus", "quicksand",
  "reindeer", "spaceship", "treasure", "universe", "volleyball", "werewolf",
  "anchor", "butterfly", "chainsaw", "drum", "elevator", "flamingo",
  "grenade", "harpoon", "icicle", "joker", "kraken", "lantern", "mermaid",
  "narwhal", "ostrich", "pretzel", "quiver", "ruler", "starfish", "throne",
  "trampoline", "utensil", "viper", "walrus", "crossbow", "yeti", "zeppelin",
  "astronaut", "boomerang", "catapult", "dynamite", "eclipse", "fossil",
  "gladiator", "hologram", "illusion", "jackhammer", "kaleidoscope",
  "locomotive", "marathon", "nebula", "oasis", "pirate", "quicksilver",
  "rattlesnake", "satellite", "treadmill", "avalanche", "blizzard",
  "centaur", "dungeon", "earthquake", "firework", "guillotine", "hydrant",
  "icicle", "javelin", "labyrinth", "minotaur", "olympus", "phoenix",
  "sandcastle", "tightrope", "undead", "voodoo", "whirlpool", "zodiac",
  "battery", "chandelier", "dentist", "escalator", "fingerprint", "galaxy",
  "harmonica", "inventor", "junkyard", "kingfisher", "lawnmower", "megaphone",
  "nutcracker", "origami", "porcupine", "rollercoaster", "scarecrow",
  "thunderstorm", "underwear", "ventriloquist", "wheelbarrow", "xray",
  "alarm clock", "bowling", "calendar", "disco ball", "earmuffs",
  "fishing rod", "gingerbread", "horseshoe", "inbox", "jacuzzi",
  "kettledrum", "lollipop", "mailbox", "nose ring", "overalls",
  "paintbrush", "quicksand", "raindrop", "snowflake", "toothbrush",
  "umbrella", "vacuum", "waffle", "zipper", "acorn", "beehive",
  "caterpillar", "dragonfly", "earthworm", "firefly", "grasshopper",
  "honeycomb", "inchworm", "ladybug", "mosquito", "pebble", "seashell",
  "tadpole", "turtle", "cobweb", "dandelion", "fern", "ivy", "moss",
  "pinecone", "sunflower", "thorn", "vine", "willow",
];
